on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment:
      name: cloudflare-pages
      url: ${{ steps.deploy.outputs.deployment-url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
